export type {
  Core_GetWalletBalancesResponse,
  Core_GetWalletSequenceResponse,
  Core_ListGlobalWalletsResponse,
  Core_ListVaultWalletsResponse,
  Core_Wallet,
  Core_WalletTag,
  CreateWalletBody,
  CreateWalletPathParams,
  DeleteWalletPathParams,
  GetWalletBalancesPathParams,
  GetWalletBalancesQueryParams,
  GetWalletByIdPathParams,
  GetWalletPathParams,
  GetWalletSequencePathParams,
  ListGlobalWalletsQueryParams,
  ListVaultWalletsPathParams,
  ListVaultWalletsQueryParams,
  SyncWalletBalancesPathParams,
  UpdateWalletBody,
  UpdateWalletPathParams,
  UpdateWalletSettingsBody,
  UpdateWalletSettingsPathParams,
} from "./wallets.types.js"
